-- DQL (Data Query Language (Linguagem de Consulta de Dados)
-- SELECT
-- INNER JOIN
-- WHERE
-- ETC()...


USE AUTOPARTS;

SELECT * FROM CUSTOMER;
SELECT * FROM C_ADDRESS;
SELECT * FROM CATEGORY;
SELECT * FROM ORDERS;
SELECT * FROM PAYMENTS;
SELECT * FROM SELLER;
SELECT * FROM SUPPLIER;
SELECT * FROM PRODUCTS;

SELECT COUNT(*) AS TOTAL FROM SUPPLIER; 


--- Tarefa 1 — Listagem Completa
--- Liste todas as peças cadastradas, trazendo:
--- ID, nome, categoria, preço e fornecedor.

select SP.ID_PRODUCTS AS
NAME_PRODUCTS, category, PRICE_PRODUCTS, NAME_PRODUCTS
from PRODUCTS PR

INNER JOIN SUPPLIER SP
ON SP.ID_PRODUCTS = PR.ID_PRODUCTS ;

--Tarefa 2 — Peças mais vendidas

--Liste as 10 peças mais vendidas com a quantidade total vendida.

SELECT top 10
  NAME_PRODUCTS, AMOUNT_PRODUCTS
FROM ORDERS 

GROUP BY AMOUNT_PRODUCTS, NAME_PRODUCTS
ORDER BY AMOUNT_PRODUCTS DESC;

--Tarefa 3 — Clientes inadimplentes

--Retorne todos os clientes com compras pendentes ou aberto.

select STATUS AS 
       ID_CUSTOMER, C_NAME
from PAYMENTS AS PA

INNER JOIN CUSTOMER AS CT
ON CT.ID_CUSTOMER = PA.ID_CUSTOMER

where status = 'PE'

-- Tarefa 4 — Estoque baixo

-- Liste as peças com quantidade em estoque menor que 5.

SELECT STOCK, 
       NAME_PRODUCTS
FROM PRODUCTS

WHERE STOCK < 5

-- Tarefa 5 — Preço médio

-- Mostre o preço médio de cada categoria de peça
SELECT
    CATEGORY,
    AVG(PRICE_PRODUCTS) AS media
FROM
    PRODUCTS
GROUP BY
    CATEGORY;

CREATE INDEX IDX_PRODCUTS_N
ON PRODUCTS(NAME_PRODUCTS);

CREATE INDEX IDX_PRODUCTS_CATEGORY
ON PRODUCTS(CATEGORY);

CREATE INDEX IDX_SUPPLIER_NAME
ON SUPPLIER(NAME_SUPPLIER);

CREATE INDEX IDX_PRODUCTS_VALUES
ON PRODUCTS(PRICE_PRODUCTS)

ALTER TABLE PRODUCTS
ADD CONSTRAINT CK_PRODUCTS_PRICE
CHECK (PRICE_PRODUCTS > 0);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CK_PRODUCTS_STOCK
CHECK (STOCK >= 0);

ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORDERS_DATE
CHECK (ORDER_DATE <= GETDATE());

ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORDERS_AMOUNT
CHECK (AMOUNT_PRODUCTS > 0);


select C_NAME from CUSTOMER

SELECT *
FROM PRODUCTS
WHERE NAME_PRODUCTS LIKE 'Filtro%';
